export const SPINNER_VERBS: string[] = [
  'thinking',
  'reasoning',
  'pondering',
  'working',
  'cooking',
  'sketching',
  'crafting',
  'chewing',
  'dreaming',
  'wondering',
  'assembling',
  'brewing',
  'compiling',
  'puzzling',
  'tracing',
  'weighing',
  'charting',
  'mulling',
  'divining',
  'stewing',
  'reaching',
  'focusing',
  'carving',
  'knitting',
  'forging',
  'tuning',
  'scanning',
  'sifting',
  'synthesizing',
  'noodling',
  'orienting',
  'hunching',
  'pacing',
  'scheming',
  'plotting',
  'spinning',
  'tracking',
  'unfolding',
  'deliberating',
  'turning',
]

export function pickVerb(): string {
  const idx = Math.floor(Math.random() * SPINNER_VERBS.length)
  return SPINNER_VERBS[idx] ?? 'thinking'
}
